#Estas dos lineas activan logging de spring y hibernate
#oracle.jdbc.fanEnabled=false
##this is not used when deployed in kubernetes. Just for local testing
spring.datasource.url=jdbc:oracle:thin:@javadev_high?TNS_ADMIN=/Users/germanavelino/Desktop/OracleTaskManager/Wallet_javadev
spring.datasource.password=Spring-boot101
##Properties of UCP
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.type=oracle.ucp.jdbc.PoolDataSource
spring.datasource.oracleucp.connection-factory-class-name=oracle.jdbc.pool.OracleDataSource
spring.datasource.oracleucp.sql-for-validate-connection=select * from dual
spring.datasource.oracleucp.connection-pool-name=connectionPoolName1
spring.datasource.oracleucp.initial-pool-size=15
spring.datasource.oracleucp.min-pool-size=10
spring.datasource.oracleucp.max-pool-size=30
##Logging properties for UCP
# COMMENT THESE LINES TO PREVENT EXCESIVE LOGGING
# logging.level.root=trace
# logging.file.name=logs.log
# logging.level.oracle.ucp=trace
# logging.level.root=trace
# logging.file.name=logs.log
# logging.level.oracle.ucp=trace
#spring.security.user.name=psong
#spring.security.user.password=WELcome__12345
telegram.bot.token=7592363904:AAE0fW__xW2U3daU5ZA2EgxyxX23GDkNuEE
telegram.bot.name=oci_java_bot
# optional, this changes the port of the development server
# set to whatever you need
server.port=8080