CREATE TABLE todo_items (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(255) NOT NULL,
    completed NUMBER(1) DEFAULT 0
);

INSERT INTO todo_items (title, completed) VALUES ('Sample Todo Item', 0);