CREATE TABLE TODOUSER.todoitem (id NUMBER GENERATED ALWAYS AS IDENTITY, description VARCHAR2(4000), creation_ts TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP, done NUMBER(1,0) , PRIMARY KEY (id));
insert into TODOUSER.todoitem  (description, done) values ('Manual item insert', 0);
CREATE TABLE TODOUSER.MANAGERS (
    MANAGER_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    ROLE VARCHAR(255),
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    CREATION_TS TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE TODOUSER.PROJECTS (
    PROJECT_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, -- Primary key for the project
    NAME VARCHAR(255) NOT NULL,                              -- Name of the project
    DESCRIPTION VARCHAR(4000),                              -- Description of the project
    CREATION_TS TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP, -- Timestamp for creation
    MANAGER_ID INT,                                         -- Foreign key to the MANAGERS table
    CONSTRAINT FK_PROJECT_MANAGER FOREIGN KEY (MANAGER_ID) REFERENCES TODOUSER.MANAGERS(MANAGER_ID) ON DELETE CASCADE
);
CREATE TABLE TODOUSER.SPRINTS (
    SPRINT_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    START_DATE TIMESTAMP WITH TIME ZONE,
    END_DATE TIMESTAMP WITH TIME ZONE,
    PROJECT_ID INT,
    CONSTRAINT FK_SPRINT_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES TODOUSER.PROJECTS(PROJECT_ID) ON DELETE CASCADE
);
CREATE TABLE TODOUSER.USERS (
    USER_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    ROLE VARCHAR(255),
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    CREATION_TS TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    MANAGER_ID INT,
    CONSTRAINT FK_USER_MANAGER FOREIGN KEY (MANAGER_ID) REFERENCES TODOUSER.MANAGERS(MANAGER_ID) ON DELETE CASCADE
);
CREATE TABLE TODOUSER.TASKS (
    TASK_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(4000),
    STATUS VARCHAR(255),
    STORY_POINTS INT,
    ESTIMATED_HOURS INT,
    REAL_HOURS INT,
    SPRINT_ID INT,
    CONSTRAINT FK_TASK_SPRINT FOREIGN KEY (SPRINT_ID) REFERENCES TODOUSER.SPRINTS(SPRINT_ID) ON DELETE CASCADE
);
CREATE TABLE TODOUSER.ASSIGNMENTS (
    ASSIGNMENT_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TASK_ID INT,
    USER_ID INT,
    ASSIGNMENT_DATE TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ASSIGNMENT_TASK FOREIGN KEY (TASK_ID) REFERENCES TODOUSER.TASKS(TASK_ID) ON DELETE CASCADE,
    CONSTRAINT FK_ASSIGNMENT_USER FOREIGN KEY (USER_ID) REFERENCES TODOUSER.USERS(USER_ID) ON DELETE CASCADE
);
CREATE TABLE TODOUSER.ISSUES (
    ISSUE_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(4000),
    STATUS INT,
    CREATION_TS TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    USER_ID INT,
    SPRINT_ID INT,
    CONSTRAINT FK_ISSUE_USER FOREIGN KEY (USER_ID) REFERENCES TODOUSER.USERS(USER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_ISSUE_SPRINT FOREIGN KEY (SPRINT_ID) REFERENCES TODOUSER.SPRINTS(SPRINT_ID) ON DELETE CASCADE
);
Insert into TODOUSER.MANAGERS (CREATION_TS,EMAIL,NAME,PASSWORD,ROLE) values (to_timestamp('10/03/25 22:00:00.000000000','DD/MM/RR HH24:MI:SSXFF'),'juanito@juanito.com','Juanito','somepassword','manager');
Insert into TODOUSER.PROJECTS (CREATION_TS,DESCRIPTION,NAME,MANAGER_ID) values (to_timestamp('10/03/25 22:00:00.000000000','DD/MM/RR HH24:MI:SSXFF'),'A new project for Juanito','Juanitos Project',1);
Insert into TODOUSER.SPRINTS (END_DATE,NAME,START_DATE,PROJECT_ID) values (to_timestamp('10/03/25 22:00:00.000000000','DD/MM/RR HH24:MI:SSXFF'),'The very first sprint',to_timestamp('10/03/25 22:00:00.000000000','DD/MM/RR HH24:MI:SSXFF'),1);
Insert into TODOUSER.USERS (CREATION_TS,EMAIL,NAME,PASSWORD,ROLE,MANAGER_ID) values (to_timestamp('10/03/25 22:00:00.000000000','DD/MM/RR HH24:MI:SSXFF'),'juanitojunior@juanito.com','Juanito''s User','somepassword','Front Developer',1);
Insert into TODOUSER.TASKS (DESCRIPTION,ESTIMATED_HOURS,NAME,REAL_HOURS,STATUS,STORY_POINTS,SPRINT_ID) values ('Una nueva tarea',10,'Nueva tarea',0,'Not-started',40,1);
Insert into TODOUSER.ASSIGNMENTS (ASSIGNMENT_DATE,TASK_ID,USER_ID) values (to_timestamp('26/04/25 23:56:14.502684000','DD/MM/RR HH24:MI:SSXFF'),1,1);